schema_version = "1.0.0"

id = "t3d_gn_presets"
version = "1.6.0"
name = "T3D GN Presets"
tagline = "A versatile collection of useful node groups for Geometry Nodes"
maintainer = "Tamil Selvan"
type = "add-on"
website = "https://github.com/Tams3d/T3D-GN-Presets"
tags = ["Geometry Nodes"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Tamil Selvan"]

[permissions]
files = "To Load node groups from .blend file"
